version: "3.3"
services:

  mysql:
    image: mysql:5.7.35
    command: --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"